# Site settings
title: "Nejc Ilenic"
email: nejc.ilenic@gmail.com
description: "A personal blog."
baseurl: ""
url: "https://inejc.github.io"
title_description: "Computer scientist interested in machine learning and statistics. I enjoy participating in <a href=\"https://www.kaggle.com/nejc92\" target=\"_blank\">Kaggle competitions</a>."
title_image: "https://pbs.twimg.com/profile_images/900305982106021892/vOzewaQq_400x400.jpg"
google_analytics: "UA-104422096-1"
disqus_account:
github_repository: https://github.com/inejc/inejc.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: nejcilenic
github_username: inejc
instagram_username:
reddit_username: inejc
linkedin_link: https://www.linkedin.com/in/nejc-ilenic
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/4517300/inejc
xing_link:
facebook_link:

# Footer
footer_left: "By <a href=\"https://github.com/inejc\">Nejc Ilenic</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/inejc/inejc.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
